int red= 9;
int yel= 10;
int grn= 11;
int bly= 8;
int pink= 7;
void setup() {
pinMode(red, OUTPUT);
pinMode(yel, OUTPUT);
pinMode(grn, OUTPUT);
pinMode(bly, OUTPUT);
pinMode(pink, OUTPUT);
}
void loop() {
digitalWrite(red, HIGH);
digitalWrite(yel, HIGH );
digitalWrite(grn, HIGH );
digitalWrite(bly, HIGH );
digitalWrite(pink, HIGH );
 delay(1000);
digitalWrite(red, HIGH );
digitalWrite(yel, LOW );
digitalWrite(grn, LOW);
digitalWrite(bly, LOW );
digitalWrite(pink, LOW );
 delay(1000);
digitalWrite(red, LOW);
digitalWrite(yel, HIGH );
digitalWrite(grn, LOW);
digitalWrite(bly, LOW);
digitalWrite(pink, LOW);
 delay(1000);
digitalWrite(red, LOW); 
digitalWrite(yel, LOW );
digitalWrite(grn, HIGH );
digitalWrite(bly, LOW );
digitalWrite(pink, LOW);
 delay(1000);
digitalWrite(red, LOW); 
digitalWrite(yel, LOW );
digitalWrite(grn, LOW);
digitalWrite(bly, HIGH );
digitalWrite(pink, LOW);
 delay(1000);
digitalWrite(red, LOW); 
digitalWrite(yel, LOW );
digitalWrite(grn, LOW);
digitalWrite(bly, LOW );
digitalWrite(pink, HIGH);
 delay(1000);
digitalWrite(red, LOW); 
digitalWrite(yel, LOW );
digitalWrite(grn, LOW);
digitalWrite(bly, LOW );
digitalWrite(pink, HIGH);
 delay(1000);
digitalWrite(red, LOW); 
digitalWrite(yel, LOW );
digitalWrite(grn, LOW);
digitalWrite(bly, HIGH );
digitalWrite(pink, LOW);
 delay(1000);
digitalWrite(red, LOW); 
digitalWrite(yel, LOW );
digitalWrite(grn, HIGH );
digitalWrite(bly, LOW );
digitalWrite(pink, LOW);
 delay(1000);
digitalWrite(red, LOW);
digitalWrite(yel, HIGH );
digitalWrite(grn, LOW);
digitalWrite(bly, LOW);
digitalWrite(pink, LOW);
 delay(1000);
digitalWrite(red, HIGH );
digitalWrite(yel, LOW );
digitalWrite(grn, LOW);
digitalWrite(bly, LOW );
digitalWrite(pink, LOW );
 delay(1000);
}
